/*  SECTION 3: USER LIFETIME & LTV ANALYTICS


------------------------------------------------------------
1️) User Lifetime Duration (Active Months)
For each user, how many months were they active from first successful transaction to last?
------------------------------------------------------------ */

WITH user_activity AS (
    SELECT
        user_id,
        MIN(created_at) AS first_txn_date,
        MAX(created_at) AS last_txn_date
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT
    user_id,
    TIMESTAMPDIFF(
        MONTH,
        first_txn_date,
        last_txn_date
    ) AS active_months
FROM user_activity
ORDER BY active_months DESC;



/* ------------------------------------------------------------
2️) Average User Lifetime (Months)
On average, how long does a user remain active?
------------------------------------------------------------ */

WITH user_activity AS (
    SELECT
        user_id,
        MIN(created_at) AS first_txn_date,
        MAX(created_at) AS last_txn_date
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT
    ROUND(AVG(
        TIMESTAMPDIFF(
            MONTH,
            first_txn_date,
            last_txn_date
        )
    ), 2) AS avg_user_lifetime_months
FROM user_activity;



/* ------------------------------------------------------------
3️)  LTV per User
What is total GMV generated by each user over their lifetime?
------------------------------------------------------------ */

SELECT
    user_id,
    ROUND(SUM(amount), 2) AS lifetime_value
FROM transactions
WHERE transaction_type = 'merchant_payment'
AND status = 'SUCCESS'
GROUP BY user_id
ORDER BY lifetime_value DESC;



/* ------------------------------------------------------------
4️) Average LTV Across Users
What is the average revenue generated per user?
------------------------------------------------------------ */

SELECT
    ROUND(AVG(user_ltv), 2) AS avg_ltv
FROM (
    SELECT
        user_id,
        SUM(amount) AS user_ltv
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
) t;



/* ------------------------------------------------------------
5️) LTV Segmentation
How many users fall into LTV tiers?
------------------------------------------------------------ */

WITH user_ltv AS (
    SELECT
        user_id,
        SUM(amount) AS lifetime_value
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT
    CASE
        WHEN lifetime_value < 5000 THEN 'Low Value'
        WHEN lifetime_value BETWEEN 5000 AND 10000 THEN 'Mid Value'
        WHEN lifetime_value BETWEEN 10001 AND 20000 THEN 'High Value'
        ELSE 'Power User'
    END AS ltv_segment,

    COUNT(*) AS user_count

FROM user_ltv
GROUP BY ltv_segment
ORDER BY user_count DESC;



/* ------------------------------------------------------------
6️)  Revenue Contribution by LTV Segment

How much GMV does each LTV segment contribute?
------------------------------------------------------------ */

WITH user_ltv AS (
    SELECT
        user_id,
        SUM(amount) AS lifetime_value
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT
    CASE
        WHEN lifetime_value < 5000 THEN 'Low Value'
        WHEN lifetime_value BETWEEN 5000 AND 10000 THEN 'Mid Value'
        WHEN lifetime_value BETWEEN 10001 AND 20000 THEN 'High Value'
        ELSE 'Power User'
    END AS ltv_segment,

    COUNT(*) AS user_count,
    ROUND(SUM(lifetime_value), 2) AS segment_revenue

FROM user_ltv
GROUP BY ltv_segment
ORDER BY segment_revenue DESC;





/*
SECTION 5: COHORT & RETENTION ANALYSIS
1️)  Cohort Size by Signup Month
How many users joined each month?
------------------------------------------------------------ */

SELECT
    DATE_FORMAT(created_at, '%Y-%m') AS signup_month,
    COUNT(*) AS cohort_size
FROM users
GROUP BY signup_month
ORDER BY signup_month;



/* ------------------------------------------------------------
2️) Month 1 Retention Rate
What % of users returned in the next month after signup?
------------------------------------------------------------ */

WITH signup_cohort AS (
    SELECT
        user_id,
        DATE_FORMAT(created_at, '%Y-%m') AS signup_month
    FROM users
),

activity AS (
    SELECT
        u.user_id,
        DATE_FORMAT(u.created_at, '%Y-%m') AS signup_month,
        TIMESTAMPDIFF(MONTH, u.created_at, t.created_at) AS month_offset
    FROM users u
    JOIN transactions t
        ON u.user_id = t.user_id
    WHERE t.transaction_type = 'merchant_payment'
    AND t.status = 'SUCCESS'
    AND t.created_at >= u.created_at
)

SELECT
    s.signup_month,
    COUNT(DISTINCT s.user_id) AS cohort_size,

    COUNT(DISTINCT CASE 
        WHEN a.month_offset = 1 
        THEN a.user_id 
    END) AS returned_m1,

    ROUND(
        COUNT(DISTINCT CASE 
            WHEN a.month_offset = 1 
            THEN a.user_id 
        END)
        / COUNT(DISTINCT s.user_id) * 100,
    2) AS retention_m1_percent

FROM signup_cohort s
LEFT JOIN activity a
    ON s.user_id = a.user_id

GROUP BY s.signup_month
ORDER BY s.signup_month;



/* ------------------------------------------------------------
3️)  Retention Decay (M0–M3)
How does retention decline over time?
------------------------------------------------------------ */

WITH signup_cohort AS (
    SELECT
        user_id,
        DATE_FORMAT(created_at, '%Y-%m') AS signup_month
    FROM users
),

activity AS (
    SELECT
        u.user_id,
        DATE_FORMAT(u.created_at, '%Y-%m') AS signup_month,
        TIMESTAMPDIFF(MONTH, u.created_at, t.created_at) AS month_offset
    FROM users u
    JOIN transactions t
        ON u.user_id = t.user_id
    WHERE t.transaction_type = 'merchant_payment'
    AND t.status = 'SUCCESS'
    AND t.created_at >= u.created_at
)

SELECT
    s.signup_month,

    ROUND(
        COUNT(DISTINCT CASE WHEN a.month_offset = 0 THEN a.user_id END)
        / COUNT(DISTINCT s.user_id) * 100,
    2) AS retention_m0,

    ROUND(
        COUNT(DISTINCT CASE WHEN a.month_offset = 1 THEN a.user_id END)
        / COUNT(DISTINCT s.user_id) * 100,
    2) AS retention_m1,

    ROUND(
        COUNT(DISTINCT CASE WHEN a.month_offset = 2 THEN a.user_id END)
        / COUNT(DISTINCT s.user_id) * 100,
    2) AS retention_m2,

    ROUND(
        COUNT(DISTINCT CASE WHEN a.month_offset = 3 THEN a.user_id END)
        / COUNT(DISTINCT s.user_id) * 100,
    2) AS retention_m3

FROM signup_cohort s
LEFT JOIN activity a
    ON s.user_id = a.user_id

GROUP BY s.signup_month
ORDER BY s.signup_month;



/* ------------------------------------------------------------
4️)  Best Performing Cohort
Which cohort has highest Month 1 retention?
------------------------------------------------------------ */

WITH retention AS (
    WITH signup_cohort AS (
        SELECT
            user_id,
            DATE_FORMAT(created_at, '%Y-%m') AS signup_month
        FROM users
    ),

    activity AS (
        SELECT
            u.user_id,
            DATE_FORMAT(u.created_at, '%Y-%m') AS signup_month,
            TIMESTAMPDIFF(MONTH, u.created_at, t.created_at) AS month_offset
        FROM users u
        JOIN transactions t
            ON u.user_id = t.user_id
        WHERE t.transaction_type = 'merchant_payment'
        AND t.status = 'SUCCESS'
        AND t.created_at >= u.created_at
    )

    SELECT
        s.signup_month,
        ROUND(
            COUNT(DISTINCT CASE 
                WHEN a.month_offset = 1 
                THEN a.user_id 
            END)
            / COUNT(DISTINCT s.user_id) * 100,
        2) AS retention_m1_percent

    FROM signup_cohort s
    LEFT JOIN activity a
        ON s.user_id = a.user_id

    GROUP BY s.signup_month
)

SELECT *
FROM retention
ORDER BY retention_m1_percent DESC
LIMIT 1;
