/* 
SECTION 1: REVENUE & MONETIZATION ANALYTICS ------------------------------------------------------------
1) Total GMV
What is total successful merchant payment volume?
------------------------------------------------------------ */

SELECT 
    ROUND(SUM(amount), 2) AS total_gmv
FROM transactions
WHERE transaction_type = 'merchant_payment'
AND status = 'SUCCESS';



/* ------------------------------------------------------------
2) Total Transaction Volume
How many successful merchant payment transactions occurred?
------------------------------------------------------------ */

SELECT 
    COUNT(*) AS total_transactions
FROM transactions
WHERE transaction_type = 'merchant_payment'
AND status = 'SUCCESS';



/* ------------------------------------------------------------
3) Average Transaction Value
What is the average ticket size of merchant payments?
------------------------------------------------------------ */

SELECT 
    ROUND(AVG(amount), 2) AS avg_transaction_value
FROM transactions
WHERE transaction_type = 'merchant_payment'
AND status = 'SUCCESS';



/* ------------------------------------------------------------
4) Monthly GMV Trend
How does merchant payment revenue trend over time?
------------------------------------------------------------ */

SELECT 
    DATE_FORMAT(created_at, '%Y-%m') AS month,
    ROUND(SUM(amount), 2) AS monthly_gmv
FROM transactions
WHERE transaction_type = 'merchant_payment'
AND status = 'SUCCESS'
GROUP BY month
ORDER BY month;



/* ------------------------------------------------------------
5) Top Merchants by GMV
Which merchants generate the highest payment volume?
------------------------------------------------------------ */

SELECT 
    m.merchant_id,
    m.merchant_name,
    ROUND(SUM(t.amount), 2) AS merchant_gmv
FROM transactions t
JOIN merchants m 
    ON t.merchant_id = m.merchant_id
WHERE t.transaction_type = 'merchant_payment'
AND t.status = 'SUCCESS'
GROUP BY m.merchant_id, m.merchant_name
ORDER BY merchant_gmv DESC
LIMIT 10;



/* ------------------------------------------------------------
6) Top Merchants by Transaction Count
Which merchants process the most transactions?
------------------------------------------------------------ */

SELECT 
    m.merchant_id,
    m.merchant_name,
    COUNT(*) AS transaction_count
FROM transactions t
JOIN merchants m 
    ON t.merchant_id = m.merchant_id
WHERE t.transaction_type = 'merchant_payment'
AND t.status = 'SUCCESS'
GROUP BY m.merchant_id, m.merchant_name
ORDER BY transaction_count DESC
LIMIT 10;



/* ------------------------------------------------------------
7) High-Value User Contribution
What % of GMV comes from users spending above 10K?
------------------------------------------------------------ */

WITH user_gmv AS (
    SELECT 
        user_id,
        SUM(amount) AS gmv
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT 
    ROUND(
        SUM(CASE WHEN gmv > 10000 THEN gmv ELSE 0 END)
        / SUM(gmv) * 100,
    2) AS high_value_gmv_percent
FROM user_gmv;



/* ------------------------------------------------------------
8) Cumulative GMV Distribution (Pareto)
How concentrated is revenue across users?
------------------------------------------------------------ */

WITH user_gmv AS (
    SELECT 
        user_id,
        SUM(amount) AS gmv
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
)

SELECT 
    user_id,
    gmv,
    ROUND(
        SUM(gmv) OVER (ORDER BY gmv DESC) 
        / SUM(gmv) OVER () * 100,
    2) AS cumulative_gmv_percent,
    ROW_NUMBER() OVER (ORDER BY gmv DESC) AS rn
FROM user_gmv
ORDER BY gmv DESC;



/* ------------------------------------------------------------
9) Top 20% User Contribution
What % of GMV is generated by the top 20% users?
------------------------------------------------------------ */

WITH user_gmv AS (
    SELECT 
        user_id,
        SUM(amount) AS gmv
    FROM transactions
    WHERE transaction_type = 'merchant_payment'
    AND status = 'SUCCESS'
    GROUP BY user_id
),

ranked_users AS (
    SELECT 
        user_id,
        gmv,
        ROW_NUMBER() OVER (ORDER BY gmv DESC) AS rn,
        COUNT(*) OVER () AS total_users
    FROM user_gmv
)

SELECT 
    ROUND(
        SUM(gmv) / (SELECT SUM(gmv) FROM user_gmv) * 100,
    2) AS top_20_percent_contribution
FROM ranked_users
WHERE rn <= total_users * 0.2;
